name: 'SWM'

# on: # ['push', 'pull_request'] 등으로도 작성 가능
#   push:
#     branches: # 특정 브랜치에 푸시가 일어났을 때만 한다
#       - main
#       - 'feature/*'
#     paths: # 특정 경로에 푸시가 일어났을 때만 한다
#       - 'src/*'
#       - 'test/*'
#   pull_request:
#     branches:
#       - main  

on: push

env:
  GLOBAL_LEVEL: "GLOBAL VALUE"

jobs: # 빌드서버를 제공. job 하나하나가 빌드서버 하나하나임. 디폴트는 순차실행이 아니라 병렬적 실행
  first-job:
    name: 'First Job'

    strategy: # 나는 운영체제를 이 3가지를 돌리고 싶다
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        nodejs: ['16',  '18']

    runs-on: ${{matrix.os}}

    steps: # 스텝들은 순서대로 실행됨
    - name: Say Hello World 1 - ${{matrix.os}}
      shell: bash
      run: |
        echo "OS: ${{matrix.os}}"
        echo "Node version: ${{matrix.nodejs}}"


# echo "GLOBAL: $GLOBAL_LEVEL" : 배시쉘 문법
# echo "JOB 1: ${{env.JOB_LEVEL_1}}" : 깃허브 액션 문법
