name: 'SWM'

# on: # ['push', 'pull_request'] 등으로도 작성 가능
#   push:
#     branches: # 특정 브랜치에 푸시가 일어났을 때만 한다
#       - main
#       - 'feature/*'
#     paths: # 특정 경로에 푸시가 일어났을 때만 한다
#       - 'src/*'
#       - 'test/*'
#   pull_request:
#     branches:
#       - main  

on: push

env:
  GLOBAL_LEVEL: "GLOBAL VALUE"

jobs: # 빌드서버를 제공. job 하나하나가 빌드서버 하나하나임. 디폴트는 순차실행이 아니라 병렬적 실행
  first-job:
    name: 'First Job'

    runs-on: ubuntu-latest

    steps: # 스텝들은 순서대로 실행됨
    - name: Say Hello World 1
      shell: bash
      run: |
        echo "Hello world from step 1"

        randomValue="swm$(echo $RANDOM)"

        echo "STEP_VALUE=$randomValue" >> $GITHUB_ENV
    

    - name: Say Hello World 2
      shell: pwsh
      run: |
        echo "Hello world from step 2"
        echo "STEP_VALUE: ${{env.STEP_VALUE}}"

  second-job:
    name: 'Second Job'

    runs-on: ubuntu-latest

    steps: # 스텝들은 순서대로 실행됨
    - name: Say Hello World 1
      shell: pwsh
      run: |
        echo "Hello world from step 1"
    
    - name: Say Hello World 2
      shell: bash
      run: |
        echo "Hello world from step 2"


# echo "GLOBAL: $GLOBAL_LEVEL" : 배시쉘 문법
# echo "JOB 1: ${{env.JOB_LEVEL_1}}" : 깃허브 액션 문법
